package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

/**
 * Campaign generated by hbm2java
 */
public class Campaign implements java.io.Serializable {

    private int id;
    private Company company;
    private CompanyDatabase companyDatabase;
    private Prize prizeByPrizeForRefiereId;
    private Prize prizeByPrizeForRefereeId;
    private String name;
    private String prizeForRefiere;
    private String prizeForReferee;

    public Campaign() {
    }

    public Campaign(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Campaign(int id, Company company, CompanyDatabase companyDatabase, Prize prizeByPrizeForRefiereId,
            Prize prizeByPrizeForRefereeId, String name, String prizeForRefiere, String prizeForReferee) {
        this.id = id;
        this.company = company;
        this.companyDatabase = companyDatabase;
        this.prizeByPrizeForRefiereId = prizeByPrizeForRefiereId;
        this.prizeByPrizeForRefereeId = prizeByPrizeForRefereeId;
        this.name = name;
        this.prizeForRefiere = prizeForRefiere;
        this.prizeForReferee = prizeForReferee;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CompanyDatabase getCompanyDatabase() {
        return this.companyDatabase;
    }

    public void setCompanyDatabase(CompanyDatabase companyDatabase) {
        this.companyDatabase = companyDatabase;
    }

    public Prize getPrizeByPrizeForRefiereId() {
        return this.prizeByPrizeForRefiereId;
    }

    public void setPrizeByPrizeForRefiereId(Prize prizeByPrizeForRefiereId) {
        this.prizeByPrizeForRefiereId = prizeByPrizeForRefiereId;
    }

    public Prize getPrizeByPrizeForRefereeId() {
        return this.prizeByPrizeForRefereeId;
    }

    public void setPrizeByPrizeForRefereeId(Prize prizeByPrizeForRefereeId) {
        this.prizeByPrizeForRefereeId = prizeByPrizeForRefereeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrizeForRefiere() {
        return this.prizeForRefiere;
    }

    public void setPrizeForRefiere(String prizeForRefiere) {
        this.prizeForRefiere = prizeForRefiere;
    }

    public String getPrizeForReferee() {
        return this.prizeForReferee;
    }

    public void setPrizeForReferee(String prizeForReferee) {
        this.prizeForReferee = prizeForReferee;
    }

}
