package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CompanyDatabase generated by hbm2java
 */
public class CompanyDatabase implements java.io.Serializable {

    private int id;
    private String name;
    private int company_id;
    private Set campaigns = new HashSet(0);
    private Set persons = new HashSet(0);

    public CompanyDatabase() {
    }

    public CompanyDatabase(int id, String name, int company_id) {
        this.id = id;
        this.name = name;
        this.company_id = company_id;
    }

    public CompanyDatabase(int id, String name, int company_id, Set campaigns, Set persons) {
        this.id = id;
        this.name = name;
        this.company_id = company_id;
        this.campaigns = campaigns;
        this.persons = persons;
    }

    public int getCompany_id() {
        return company_id;
    }

    public void setCompany_id(int company_id) {
        this.company_id = company_id;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getCampaigns() {
        return this.campaigns;
    }

    public void setCampaigns(Set campaigns) {
        this.campaigns = campaigns;
    }

    public Set getPersons() {
        return this.persons;
    }

    public void setPersons(Set persons) {
        this.persons = persons;
    }

}
