package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

    private int id;
    private String name;
    private String address;
    private String email;
    private String phone;
    private Set campaigns = new HashSet(0);
    private Set planOrders = new HashSet(0);
    private Set userCompanies = new HashSet(0);

    public Company() {
    }

    public Company(int id) {
        this.id = id;
    }

    public Company(int id, String name, String address, String email, String phone, Set campaigns, Set planOrders,
            Set userCompanies) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.campaigns = campaigns;
        this.planOrders = planOrders;
        this.userCompanies = userCompanies;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Set getCampaigns() {
        return this.campaigns;
    }

    public void setCampaigns(Set campaigns) {
        this.campaigns = campaigns;
    }

    public Set getPlanOrders() {
        return this.planOrders;
    }

    public void setPlanOrders(Set planOrders) {
        this.planOrders = planOrders;
    }

    public Set getUserCompanies() {
        return this.userCompanies;
    }

    public void setUserCompanies(Set userCompanies) {
        this.userCompanies = userCompanies;
    }

    public String toJson() {
        return "{\"name\": " + name + ", \"address:\" " + address + ", \"email:\" " + email + ", \"phone:\" "  + phone + "}";
    }
}
