package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

    private int id;
    private String currencyId;
    private String currencyDescription;
    private Set planPrices = new HashSet(0);
    private Set payments = new HashSet(0);

    public Currency() {
    }

    public Currency(int id, String currencyId, String currencyDescription) {
        this.id = id;
        this.currencyId = currencyId;
        this.currencyDescription = currencyDescription;
    }

    public Currency(int id, String currencyId, String currencyDescription, Set planPrices, Set payments) {
        this.id = id;
        this.currencyId = currencyId;
        this.currencyDescription = currencyDescription;
        this.planPrices = planPrices;
        this.payments = payments;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(String currencyId) {
        this.currencyId = currencyId;
    }

    public String getCurrencyDescription() {
        return this.currencyDescription;
    }

    public void setCurrencyDescription(String currencyDescription) {
        this.currencyDescription = currencyDescription;
    }

    public Set getPlanPrices() {
        return this.planPrices;
    }

    public void setPlanPrices(Set planPrices) {
        this.planPrices = planPrices;
    }

    public Set getPayments() {
        return this.payments;
    }

    public void setPayments(Set payments) {
        this.payments = payments;
    }

}
