package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lapse generated by hbm2java
 */
public class Lapse implements java.io.Serializable {

    private int id;
    private String name;
    private int days;
    private Set plansForCampaignLapseRef = new HashSet(0);
    private Set plansForReportLapseId = new HashSet(0);

    public Lapse() {
    }

    public Lapse(int id, String name, int days) {
        this.id = id;
        this.name = name;
        this.days = days;
    }

    public Lapse(int id, String name, int days, Set plansForCampaignLapseRef, Set plansForReportLapseId) {
        this.id = id;
        this.name = name;
        this.days = days;
        this.plansForCampaignLapseRef = plansForCampaignLapseRef;
        this.plansForReportLapseId = plansForReportLapseId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getDays() {
        return this.days;
    }

    public void setDays(int days) {
        this.days = days;
    }

    public Set getPlansForCampaignLapseRef() {
        return this.plansForCampaignLapseRef;
    }

    public void setPlansForCampaignLapseRef(Set plansForCampaignLapseRef) {
        this.plansForCampaignLapseRef = plansForCampaignLapseRef;
    }

    public Set getPlansForReportLapseId() {
        return this.plansForReportLapseId;
    }

    public void setPlansForReportLapseId(Set plansForReportLapseId) {
        this.plansForReportLapseId = plansForReportLapseId;
    }

}
