package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

    private int id;
    private String name;
    private String description;
    private Set planOrders = new HashSet(0);

    public OrderStatus() {
    }

    public OrderStatus(int id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    public OrderStatus(int id, String name, String description, Set planOrders) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.planOrders = planOrders;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPlanOrders() {
        return this.planOrders;
    }

    public void setPlanOrders(Set planOrders) {
        this.planOrders = planOrders;
    }

}
