package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

    private int id;
    private Currency currency;
    private PaymentType paymentType;
    private String paymentDescription;
    private BigDecimal price;
    private BigDecimal discount;
    private BigDecimal totalPrice;
    private Set planOrders = new HashSet(0);

    public Payment() {
    }

    public Payment(int id, BigDecimal price, BigDecimal totalPrice) {
        this.id = id;
        this.price = price;
        this.totalPrice = totalPrice;
    }

    public Payment(int id, Currency currency, PaymentType paymentType, String paymentDescription, BigDecimal price,
            BigDecimal discount, BigDecimal totalPrice, Set planOrders) {
        this.id = id;
        this.currency = currency;
        this.paymentType = paymentType;
        this.paymentDescription = paymentDescription;
        this.price = price;
        this.discount = discount;
        this.totalPrice = totalPrice;
        this.planOrders = planOrders;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Currency getCurrency() {
        return this.currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public PaymentType getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

    public String getPaymentDescription() {
        return this.paymentDescription;
    }

    public void setPaymentDescription(String paymentDescription) {
        this.paymentDescription = paymentDescription;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    public Set getPlanOrders() {
        return this.planOrders;
    }

    public void setPlanOrders(Set planOrders) {
        this.planOrders = planOrders;
    }

}
