package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * PaymentType generated by hbm2java
 */
public class PaymentType implements java.io.Serializable {

    private int id;
    private String typeDescription;
    private Set payments = new HashSet(0);

    public PaymentType() {
    }

    public PaymentType(int id, String typeDescription) {
        this.id = id;
        this.typeDescription = typeDescription;
    }

    public PaymentType(int id, String typeDescription, Set payments) {
        this.id = id;
        this.typeDescription = typeDescription;
        this.payments = payments;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTypeDescription() {
        return this.typeDescription;
    }

    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription;
    }

    public Set getPayments() {
        return this.payments;
    }

    public void setPayments(Set payments) {
        this.payments = payments;
    }

}
