package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * PlanPrice generated by hbm2java
 */
public class PlanPrice implements java.io.Serializable {

    private int id;
    private Currency currency;
    private Plan plan;
    private BigDecimal price;
    private String description;

    public PlanPrice() {
    }

    public PlanPrice(int id, BigDecimal price, String description) {
        this.id = id;
        this.price = price;
        this.description = description;
    }

    public PlanPrice(int id, Currency currency, Plan plan, BigDecimal price, String description) {
        this.id = id;
        this.currency = currency;
        this.plan = plan;
        this.price = price;
        this.description = description;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Currency getCurrency() {
        return this.currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public Plan getPlan() {
        return this.plan;
    }

    public void setPlan(Plan plan) {
        this.plan = plan;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
