package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PlanOrderHistory generated by hbm2java
 */
public class PlanOrderHistory implements java.io.Serializable {

    private String id;
    private PlanOrder planOrder;
    private int paymentId;
    private int statusId;
    private int companyId;
    private String approvedBy;
    private String changeBy;
    private Date changeDate;
    private Date startDate;
    private Date endDate;

    public PlanOrderHistory() {
    }

    public PlanOrderHistory(String id, int paymentId, int statusId, int companyId, String approvedBy, String changeBy,
            Date changeDate, Date startDate, Date endDate) {
        this.id = id;
        this.paymentId = paymentId;
        this.statusId = statusId;
        this.companyId = companyId;
        this.approvedBy = approvedBy;
        this.changeBy = changeBy;
        this.changeDate = changeDate;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public PlanOrderHistory(String id, PlanOrder planOrder, int paymentId, int statusId, int companyId,
            String approvedBy, String changeBy, Date changeDate, Date startDate, Date endDate) {
        this.id = id;
        this.planOrder = planOrder;
        this.paymentId = paymentId;
        this.statusId = statusId;
        this.companyId = companyId;
        this.approvedBy = approvedBy;
        this.changeBy = changeBy;
        this.changeDate = changeDate;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public PlanOrder getPlanOrder() {
        return this.planOrder;
    }

    public void setPlanOrder(PlanOrder planOrder) {
        this.planOrder = planOrder;
    }

    public int getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    public int getStatusId() {
        return this.statusId;
    }

    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    public int getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    public String getApprovedBy() {
        return this.approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    public String getChangeBy() {
        return this.changeBy;
    }

    public void setChangeBy(String changeBy) {
        this.changeBy = changeBy;
    }

    public Date getChangeDate() {
        return this.changeDate;
    }

    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

}
