package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

    private int id;
    private Lapse lapseByCampaignLapseRef;
    private Lapse lapseByReportLapseId;
    private int campaignAmount;
    private String name;
    private int referrerAmount;
    private BigDecimal salesPercentaje;
    private boolean isActive;
    private Set planPrices = new HashSet(0);
    private Set planOrders = new HashSet(0);

    public Plan() {
    }

    public Plan(int id, int campaignAmount, int referrerAmount, BigDecimal salesPercentaje,
            boolean isActive) {
        this.id = id;
        this.campaignAmount = campaignAmount;
        this.referrerAmount = referrerAmount;
        this.salesPercentaje = salesPercentaje;
        this.isActive = isActive;
    }

    public Plan(int id, Lapse lapseByCampaignLapseRef, Lapse lapseByReportLapseId, int campaignAmount, String name,
             int referrerAmount, BigDecimal salesPercentaje, boolean isActive,
            Set planPrices, Set planOrders) {
        this.id = id;
        this.lapseByCampaignLapseRef = lapseByCampaignLapseRef;
        this.lapseByReportLapseId = lapseByReportLapseId;
        this.campaignAmount = campaignAmount;
        this.name = name;
        this.referrerAmount = referrerAmount;
        this.salesPercentaje = salesPercentaje;
        this.isActive = isActive;
        this.planPrices = planPrices;
        this.planOrders = planOrders;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Lapse getLapseByCampaignLapseRef() {
        return this.lapseByCampaignLapseRef;
    }

    public void setLapseByCampaignLapseRef(Lapse lapseByCampaignLapseRef) {
        this.lapseByCampaignLapseRef = lapseByCampaignLapseRef;
    }

    public Lapse getLapseByReportLapseId() {
        return this.lapseByReportLapseId;
    }

    public void setLapseByReportLapseId(Lapse lapseByReportLapseId) {
        this.lapseByReportLapseId = lapseByReportLapseId;
    }

    public int getCampaignAmount() {
        return this.campaignAmount;
    }

    public void setCampaignAmount(int campaignAmount) {
        this.campaignAmount = campaignAmount;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getReferrerAmount() {
        return this.referrerAmount;
    }

    public void setReferrerAmount(int referrerAmount) {
        this.referrerAmount = referrerAmount;
    }

    public BigDecimal getSalesPercentaje() {
        return this.salesPercentaje;
    }

    public void setSalesPercentaje(BigDecimal salesPercentaje) {
        this.salesPercentaje = salesPercentaje;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Set getPlanPrices() {
        return this.planPrices;
    }

    public void setPlanPrices(Set planPrices) {
        this.planPrices = planPrices;
    }

    public Set getPlanOrders() {
        return this.planOrders;
    }

    public void setPlanOrders(Set planOrders) {
        this.planOrders = planOrders;
    }

}
