package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

/**
 * ReferencesCodesId generated by hbm2java
 */
public class ReferencesCodesId implements java.io.Serializable {

    private int campaignId;
    private int personId;

    public ReferencesCodesId() {
    }

    public ReferencesCodesId(int campaignId, int personId) {
        this.campaignId = campaignId;
        this.personId = personId;
    }

    public int getCampaignId() {
        return this.campaignId;
    }

    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }

    public int getPersonId() {
        return this.personId;
    }

    public void setPersonId(int personId) {
        this.personId = personId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ReferencesCodesId))
            return false;
        ReferencesCodesId castOther = (ReferencesCodesId) other;

        return (this.getCampaignId() == castOther.getCampaignId()) && (this.getPersonId() == castOther.getPersonId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCampaignId();
        result = 37 * result + this.getPersonId();
        return result;
    }

}
