package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

/**
 * ReferencesCodes generated by hbm2java
 */
public class ReferencesCodes implements java.io.Serializable {

    private ReferencesCodesId id;
    private Person person;
    
    public ReferencesCodes() {
    }
    
    public ReferencesCodes(ReferencesCodesId id, Person person) {
        this.id = id;
        this.person = person;
    }

    public ReferencesCodes(Person person) {
        this.person = person;
    }

    public ReferencesCodesId getId() {
        return this.id;
    }

    public void setId(ReferencesCodesId id) {
        this.id = id;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

}
