package co.refiere.models;
// Generated Apr 15, 2016 11:32:27 AM by Hibernate Tools 4.3.1.Final

/**
 * RefiereUserCompany generated by hbm2java
 */
public class RefiereUserCompany implements java.io.Serializable {

	private String id;
	private RefiereCompany refiereCompanyByUserId;
	private RefiereCompany refiereCompanyByCompanyId;

	public RefiereUserCompany() {
	}

	public RefiereUserCompany(String id) {
		this.id = id;
	}

	public RefiereUserCompany(String id, RefiereCompany refiereCompanyByUserId,
			RefiereCompany refiereCompanyByCompanyId) {
		this.id = id;
		this.refiereCompanyByUserId = refiereCompanyByUserId;
		this.refiereCompanyByCompanyId = refiereCompanyByCompanyId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public RefiereCompany getRefiereCompanyByUserId() {
		return this.refiereCompanyByUserId;
	}

	public void setRefiereCompanyByUserId(RefiereCompany refiereCompanyByUserId) {
		this.refiereCompanyByUserId = refiereCompanyByUserId;
	}

	public RefiereCompany getRefiereCompanyByCompanyId() {
		return this.refiereCompanyByCompanyId;
	}

	public void setRefiereCompanyByCompanyId(RefiereCompany refiereCompanyByCompanyId) {
		this.refiereCompanyByCompanyId = refiereCompanyByCompanyId;
	}

}
