package co.refiere.models;
// Generated Apr 15, 2016 1:30:24 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * RefiereUser generated by hbm2java
 */
public class RefiereUser implements java.io.Serializable {

    private int id;
    private String login;
    private String password;
    private Set refiereUserCompanies = new HashSet(0);

    public RefiereUser() {
    }

    public RefiereUser(int id, String login, String password) {
        this.id = id;
        this.login = login;
        this.password = password;
    }

    public RefiereUser(int id, String login, String password, Set refiereUserCompanies) {
        this.id = id;
        this.login = login;
        this.password = password;
        this.refiereUserCompanies = refiereUserCompanies;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getRefiereUserCompanies() {
        return this.refiereUserCompanies;
    }

    public void setRefiereUserCompanies(Set refiereUserCompanies) {
        this.refiereUserCompanies = refiereUserCompanies;
    }

}
