package co.refiere.models;
// Generated Apr 15, 2016 6:14:42 PM by Hibernate Tools 4.3.1.Final

import co.refiere.models.RefiereCompany;
import co.refiere.models.RefiereUser;

/**
 * RefiereUserCompany generated by hbm2java
 */
public class RefiereUserCompany implements java.io.Serializable {

    private int id;
    private RefiereCompany refiereCompany;
    private RefiereUser refiereUser;

    public RefiereUserCompany() {
    }

    public RefiereUserCompany(int id, RefiereCompany refiereCompany, RefiereUser refiereUser) {
        this.id = id;
        this.refiereCompany = refiereCompany;
        this.refiereUser = refiereUser;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public RefiereCompany getRefiereCompany() {
        return this.refiereCompany;
    }

    public void setRefiereCompany(RefiereCompany refiereCompany) {
        this.refiereCompany = refiereCompany;
    }

    public RefiereUser getRefiereUser() {
        return this.refiereUser;
    }

    public void setRefiereUser(RefiereUser refiereUser) {
        this.refiereUser = refiereUser;
    }

}
