package co.refiere.models;
// Generated Apr 19, 2016 12:44:33 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import co.refiere.models.UserRoles;

/**
 * SimpleUser generated by hbm2java
 */
public class SimpleUser implements java.io.Serializable {

    private int id;
    private UserRoles userRoles;
    private String login;
    private String password;
    private Set userCompanies = new HashSet(0);

    public SimpleUser() {
    }

    public SimpleUser(int id, String login, String password) {
        this.id = id;
        this.login = login;
        this.password = password;
    }

    public SimpleUser(int id, UserRoles userRoles, String login, String password, Set userCompanies) {
        this.id = id;
        this.userRoles = userRoles;
        this.login = login;
        this.password = password;
        this.userCompanies = userCompanies;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public UserRoles getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(UserRoles userRoles) {
        this.userRoles = userRoles;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getUserCompanies() {
        return this.userCompanies;
    }

    public void setUserCompanies(Set userCompanies) {
        this.userCompanies = userCompanies;
    }

}
