package co.refiere.models;
// Generated Apr 19, 2016 12:44:33 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

    private int id;
    private String roleIdentifier;
    private String description;
    private String name;
    private Set simpleUsers = new HashSet(0);

    public UserRoles() {
    }

    public UserRoles(int id, String roleIdentifier, String description, String name) {
        this.id = id;
        this.roleIdentifier = roleIdentifier;
        this.description = description;
        this.name = name;
    }

    public UserRoles(int id, String roleIdentifier, String description, String name, Set simpleUsers) {
        this.id = id;
        this.roleIdentifier = roleIdentifier;
        this.description = description;
        this.name = name;
        this.simpleUsers = simpleUsers;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRoleIdentifier() {
        return this.roleIdentifier;
    }

    public void setRoleIdentifier(String roleIdentifier) {
        this.roleIdentifier = roleIdentifier;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getSimpleUsers() {
        return this.simpleUsers;
    }

    public void setSimpleUsers(Set simpleUsers) {
        this.simpleUsers = simpleUsers;
    }

}
