package co.refiere.models;
// Generated Apr 19, 2016 11:27:45 AM by Hibernate Tools 4.3.1.Final

/**
 * UserCompany generated by hbm2java
 */
public class UserCompany implements java.io.Serializable {

    private int id;
    private Company company;
    private SimpleUser simpleUser;

    public UserCompany() {
    }

    public UserCompany(int id) {
        this.id = id;
    }

    public UserCompany(int id, Company company, SimpleUser simpleUser) {
        this.id = id;
        this.company = company;
        this.simpleUser = simpleUser;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public SimpleUser getSimpleUser() {
        return this.simpleUser;
    }

    public void setSimpleUser(SimpleUser simpleUser) {
        this.simpleUser = simpleUser;
    }

}
